{
  "formatVersion": "1.1",
  "component": {
    "group": "net.beltaria",
    "module": "beltariaspigot-api",
    "version": "1.8.8-R0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.avaje",
          "module": "ebean",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.33"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.8-SNAPSHOT"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "18.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.35"
          }
        },
        {
          "group": "net.sf.trove4j",
          "module": "trove4j",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT.jar",
          "url": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT.jar",
          "size": 998795,
          "sha512": "69793a0c2c009e71a89635f949636dc93655e74aa27c344741931974ec87cb457a438273ef8829c86967ee9622841617042f096a1f123bc130b530ca8ce798ce",
          "sha256": "b059867e5cad370a0841e6763c54e327e738d098e708ca2afc433f2beadf0b07",
          "sha1": "df1abc5171b0d69cec5d49109a5775a17bb1786f",
          "md5": "8ab5c1ec45204e438c55099573909d33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.avaje",
          "module": "ebean",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.33"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.8-SNAPSHOT"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "18.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.35"
          }
        }
      ],
      "files": [
        {
          "name": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT.jar",
          "url": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT.jar",
          "size": 998795,
          "sha512": "69793a0c2c009e71a89635f949636dc93655e74aa27c344741931974ec87cb457a438273ef8829c86967ee9622841617042f096a1f123bc130b530ca8ce798ce",
          "sha256": "b059867e5cad370a0841e6763c54e327e738d098e708ca2afc433f2beadf0b07",
          "sha1": "df1abc5171b0d69cec5d49109a5775a17bb1786f",
          "md5": "8ab5c1ec45204e438c55099573909d33"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT-sources.jar",
          "url": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT-sources.jar",
          "size": 703552,
          "sha512": "2a7000b1f6c9685ac7fbaeaa2d1e586c8975352beb020060c9b8e79348a0c4c6db5a27449a71af2ad5f22945de257333e8370afd2788182263382800cffbe24b",
          "sha256": "0163882161320f6f04de434436b26ee2e1c76ca30b0e81f6d18402c119f123b7",
          "sha1": "ff2028462464fa98e779ad756cc9c59c2fb1489b",
          "md5": "6634a507b5557fc71b664f76fab03c23"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT-javadoc.jar",
          "url": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT-javadoc.jar",
          "size": 3598216,
          "sha512": "3f809e5284cc38373a723375e40f307bf358965f589388b9c0ebfd52519b3cdde4b6d7cf4406ad3d7c3d58c5ca8c1e8645910b8797ef8f585474f6fa5eb4567f",
          "sha256": "017a3be4dde29184ce2648934a7412fc1b7541dd00e363b8232f68d6b2f1abfc",
          "sha1": "9aac383b25709d01aefa885bc31614225b370bda",
          "md5": "4cf527c0d0ac36b08a235fbab251d35f"
        }
      ]
    }
  ]
}
