{
  "formatVersion": "1.1",
  "component": {
    "group": "net.beltaria",
    "module": "beltariaspigot-api",
    "version": "1.8.8-R0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.avaje",
          "module": "ebean",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.33"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.8-SNAPSHOT"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.7.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.35"
          }
        },
        {
          "group": "net.sf.trove4j",
          "module": "trove4j",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT.jar",
          "url": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT.jar",
          "size": 998695,
          "sha512": "dd382df575baaec5a642ad06c98c39b518efa8cf87b0030ff484a30d2e92f13167ab5b2cc0076a9143195ad643cce9710a197e854ebcefedb3ae2231e59fe55d",
          "sha256": "c332715a137419440d7926dd0edeab6d3e7aafc682d15e5108ba413d30f389ee",
          "sha1": "5152323b4414a8571ee24fc9f0b8a9314d9607e2",
          "md5": "2df44cad9993f7730f6207acf6b5931d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.avaje",
          "module": "ebean",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.33"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.8-SNAPSHOT"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.7.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.35"
          }
        }
      ],
      "files": [
        {
          "name": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT.jar",
          "url": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT.jar",
          "size": 998695,
          "sha512": "dd382df575baaec5a642ad06c98c39b518efa8cf87b0030ff484a30d2e92f13167ab5b2cc0076a9143195ad643cce9710a197e854ebcefedb3ae2231e59fe55d",
          "sha256": "c332715a137419440d7926dd0edeab6d3e7aafc682d15e5108ba413d30f389ee",
          "sha1": "5152323b4414a8571ee24fc9f0b8a9314d9607e2",
          "md5": "2df44cad9993f7730f6207acf6b5931d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT-sources.jar",
          "url": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT-sources.jar",
          "size": 703552,
          "sha512": "2a7000b1f6c9685ac7fbaeaa2d1e586c8975352beb020060c9b8e79348a0c4c6db5a27449a71af2ad5f22945de257333e8370afd2788182263382800cffbe24b",
          "sha256": "0163882161320f6f04de434436b26ee2e1c76ca30b0e81f6d18402c119f123b7",
          "sha1": "ff2028462464fa98e779ad756cc9c59c2fb1489b",
          "md5": "6634a507b5557fc71b664f76fab03c23"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT-javadoc.jar",
          "url": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT-javadoc.jar",
          "size": 3598447,
          "sha512": "6cd18130caaf09362c2670efcaf0932d51177a63913d1d6c930a8859220182638916627dcc1d41df1ef5ccbe4fcc1b3d904c7ff74a9aca9de15693e67270e88a",
          "sha256": "831be2a570366ba09b55ffab44bd72c741244c3fcb4bf786d15ff6045dfef6d0",
          "sha1": "5553e4191a690a07ed66d69265c7495eddbdd04f",
          "md5": "7123f827869ec7f05e60ee710afdf5f2"
        }
      ]
    }
  ]
}
