{
  "formatVersion": "1.1",
  "component": {
    "group": "net.beltaria",
    "module": "beltariaspigot-api",
    "version": "1.8.8-R0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.avaje",
          "module": "ebean",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.8-SNAPSHOT"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "18.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.35"
          }
        },
        {
          "group": "net.sf.trove4j",
          "module": "trove4j",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT.jar",
          "url": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT.jar",
          "size": 998636,
          "sha512": "25155a2169547047ee2e1f8d108dabaeef1c846b6d27d9964add55819fea373a365d5fd431ae4310f3002c9195a61501ffb3308eb5542bca087c81cd7e134126",
          "sha256": "a3df02129c71d14dd706370b6ad6d3b5e8cfae4c6b04b5fd0c06e3f4ffa4c451",
          "sha1": "b1db7f0b467b72a5c560f6dbfbb9d481536c55d8",
          "md5": "0e4b18491cd6bc38d668dfce7c3dadb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.avaje",
          "module": "ebean",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.8-SNAPSHOT"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.35"
          }
        }
      ],
      "files": [
        {
          "name": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT.jar",
          "url": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT.jar",
          "size": 998636,
          "sha512": "25155a2169547047ee2e1f8d108dabaeef1c846b6d27d9964add55819fea373a365d5fd431ae4310f3002c9195a61501ffb3308eb5542bca087c81cd7e134126",
          "sha256": "a3df02129c71d14dd706370b6ad6d3b5e8cfae4c6b04b5fd0c06e3f4ffa4c451",
          "sha1": "b1db7f0b467b72a5c560f6dbfbb9d481536c55d8",
          "md5": "0e4b18491cd6bc38d668dfce7c3dadb8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT-sources.jar",
          "url": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT-sources.jar",
          "size": 703082,
          "sha512": "2d1549b93183f49e4aa0b7bb78deb4953f357e9a8e18344836e34936a9083d8430d564d581b8e00600d08b1ec82009f8ca9b2576dfbff421fccf82564f5b106d",
          "sha256": "9a4832bc303eb8faa6e599212175ee3ecccffbb6f6987f2f645195f366b4364e",
          "sha1": "e3434c1b77d078207c25b6b2955f9e4fd90f1713",
          "md5": "1a34e656ee32ff2fcebef6b9284d4eba"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT-javadoc.jar",
          "url": "beltariaspigot-api-1.8.8-R0.1-SNAPSHOT-javadoc.jar",
          "size": 3597757,
          "sha512": "9e5a71fff095ed45f6c011e15096cb702a388f46fc71c6b0bef7a039202518bfa73269f75d2a5cf23dc018e46cbfb6fbf15d66fe0b0749bc5af69f56c75194a2",
          "sha256": "c131721b4d01922461780d4c03b4093e5d78301b77a5456935763c2e7799703d",
          "sha1": "f5181894062f1b1f118d9ac3fd65dae6896fe341",
          "md5": "4a7f6abdce5f1e6f8cef6f47a6cdd985"
        }
      ]
    }
  ]
}
